Support dynamic paths

diff --git a/.github/workflows/test-command.yml b/.github/workflows/test-command.yml
--- a/.github/workflows/test-command.yml
+++ b/.github/workflows/test-command.yml
@@ -39,7 +39,6 @@ jobs:
     if: ${{ github.event.client_payload.slash_command.args.unnamed.arg1 == 'readme' || github.event.client_payload.slash_command.arg1 == 'readme' || github.event.client_payload.slash_command.args.unnamed.arg1 == 'all' || github.event.client_payload.slash_command.arg1 == 'all' }}
     container: cloudposse/testing.cloudposse.co:latest
     env: 
-      PATH: "/usr/local/terraform/0.13/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
       MAKE_INCLUDES: Makefile
     steps:
     # Update GitHub status for dispatch events
@@ -124,7 +123,6 @@ jobs:
     if: ${{ github.event.client_payload.slash_command.args.unnamed.arg1 == 'bats' || github.event.client_payload.slash_command.arg1 == 'bats' || github.event.client_payload.slash_command.args.unnamed.arg1 == 'all' || github.event.client_payload.slash_command.arg1 == 'all' }}
     container: cloudposse/testing.cloudposse.co:latest
     env: 
-      PATH: "/usr/local/terraform/0.13/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
       MAKE_INCLUDES: Makefile
     steps:
     # Update GitHub status for dispatch events
@@ -148,6 +146,27 @@ jobs:
         token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
         repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
         ref: ${{ github.event.client_payload.pull_request.head.ref }} 
+
+    # Determine requied version of terraform based on the target branch of the pull request. Then update the PATH to use it.
+    - name: "Determine required terraform version"
+      run: |
+        FORMAT="::set-env name=PATH::/usr/local/terraform/%s/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
+        if [[ ${GITHUB_REF} == 'refs/heads/master' ]]; then
+          echo "Requiring terraform 0.13..."
+          printf $FORMAT 0.13
+        elif [[ ${GITHUB_REF} == 'refs/heads/0.12/master' ]]; then
+          echo "Requiring terraform 0.12..."
+          printf $FORMAT 0.12
+        elif [[ ${GITHUB_REF} == 'refs/heads/0.11/master' ]]; then
+          echo "Requiring terraform 0.11..."
+          printf $FORMAT 0.11
+        else
+          echo "Unable to determine terraform version for ${GITHUB_REF}"
+          exit 1
+        fi
+      env:
+        # Pull request target branch
+        GITHUB_REF: ${{ github.event.client_payload.pull_request.base.ref }}
 
     # Initialize the test-harness which has a library of bats tests
     - name: "Initialize test-harness"
@@ -212,7 +231,6 @@ jobs:
     if: ${{ github.event.client_payload.slash_command.args.unnamed.arg1 == 'terratest' || github.event.client_payload.slash_command.arg1 == 'terratest' || github.event.client_payload.slash_command.args.unnamed.arg1 == 'all' || github.event.client_payload.slash_command.arg1 == 'all' }}
     container: cloudposse/testing.cloudposse.co:latest
     env: 
-      PATH: "/usr/local/terraform/0.13/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
       MAKE_INCLUDES: Makefile
     steps:
     # Update GitHub status for dispatch events
@@ -236,6 +254,27 @@ jobs:
         token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
         repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
         ref: ${{ github.event.client_payload.pull_request.head.ref }} 
+
+    # Determine requied version of terraform based on the target branch of the pull request. Then update the PATH to use it.
+    - name: "Determine required terraform version"
+      run: |
+        FORMAT="::set-env name=PATH::/usr/local/terraform/%s/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
+        if [[ ${GITHUB_REF} == 'refs/heads/master' ]]; then
+          echo "Requiring terraform 0.13..."
+          printf $FORMAT 0.13
+        elif [[ ${GITHUB_REF} == 'refs/heads/0.12/master' ]]; then
+          echo "Requiring terraform 0.12..."
+          printf $FORMAT 0.12
+        elif [[ ${GITHUB_REF} == 'refs/heads/0.11/master' ]]; then
+          echo "Requiring terraform 0.11..."
+          printf $FORMAT 0.11
+        else
+          echo "Unable to determine terraform version for ${GITHUB_REF}"
+          exit 1
+        fi
+      env:
+        # Pull request target branch
+        GITHUB_REF: ${{ github.event.client_payload.pull_request.base.ref }}
 
     # Initialize the terratest go project
     - name: "Initialize terratest go project"
