Fix Terraform version check (#83)

diff --git a/.github/workflows/test-command.yml b/.github/workflows/test-command.yml
--- a/.github/workflows/test-command.yml
+++ b/.github/workflows/test-command.yml
@@ -154,13 +154,15 @@ jobs:
 
     # Determine requied version of terraform based on the target branch of the pull request. Then update the PATH to use it.
     - name: "Determine required terraform version"
+      shell: bash -x -e -o pipefail {0}
       run: |
         VERSION=$(cut -d/ -f1 <<<${BASE_REF})
         if [[ ${VERSION} == 'master' ]]; then
           TF12=0.12.29
           TF13=$(terraform-0.13 version --json | jq -r .terraform_version)
           TF14=$(terraform-0.14 version --json | jq -r .terraform_version)
-          VERSION=$(vert -s "$(terraform-config-inspect --json . | jq -r '.required_core[]')" "$TF12" "$TF13" "$TF14" | head -1)
+          # vert exits non-zero if any of the versions are not acceptable, so `|| [[ -n "$VERSION" ]]` for a real error check
+          VERSION=$(vert -s "$(terraform-config-inspect --json . | jq -r '.required_core[]')" "$TF12" "$TF13" "$TF14" | head -1) || [[ -n "$VERSION" ]]
           echo Full version to use is ${VERSION}, setting to ${VERSION:0:4}
           VERSION=${VERSION:0:4}
         fi
@@ -276,13 +278,15 @@ jobs:
 
     # Determine requied version of terraform based on the target branch of the pull request. Then update the PATH to use it.
     - name: "Determine required terraform version"
+      shell: bash -x -e -o pipefail {0}
       run: |
         VERSION=$(cut -d/ -f1 <<<${BASE_REF})
         if [[ ${VERSION} == 'master' ]]; then
           TF12=0.12.29
           TF13=$(terraform-0.13 version --json | jq -r .terraform_version)
           TF14=$(terraform-0.14 version --json | jq -r .terraform_version)
-          VERSION=$(vert -s "$(terraform-config-inspect --json . | jq -r '.required_core[]')" "$TF12" "$TF13" "$TF14" | head -1)
+          # vert exits non-zero if any of the versions are not acceptable, so `|| [[ -n "$VERSION" ]]` for a real error check
+          VERSION=$(vert -s "$(terraform-config-inspect --json . | jq -r '.required_core[]')" "$TF12" "$TF13" "$TF14" | head -1) || [[ -n "$VERSION" ]]
           echo Full version to use is ${VERSION}, setting to ${VERSION:0:4}
           VERSION=${VERSION:0:4}
         fi
