Use terraform 0.13 (#42)
* Use terraform 0.13

* Support dynamic paths

* rename GITHUB_REF to BASE_REF to avoid possible conflict

* rewrite logic to determine terraform version

* change default shell to bash

* improve error handling

* allow labels to override version for testing

* replicate to other tests

* change default to 0.12

* add missing env

* fix grep exit codes

diff --git a/.github/workflows/test-command.yml b/.github/workflows/test-command.yml
--- a/.github/workflows/test-command.yml
+++ b/.github/workflows/test-command.yml
@@ -3,6 +3,11 @@ on:
   repository_dispatch:
     types: [test-command]
 
+defaults:
+  run:
+    # We need -e -o pipefail for consistency with GitHub Actions's default behavior
+    shell: bash -e -o pipefail {0}
+
 jobs:
   ack:
     runs-on: ubuntu-latest
@@ -39,7 +44,6 @@ jobs:
     if: ${{ github.event.client_payload.slash_command.args.unnamed.arg1 == 'readme' || github.event.client_payload.slash_command.arg1 == 'readme' || github.event.client_payload.slash_command.args.unnamed.arg1 == 'all' || github.event.client_payload.slash_command.arg1 == 'all' }}
     container: cloudposse/testing.cloudposse.co:latest
     env: 
-      PATH: "/usr/local/terraform/0.12/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
       MAKE_INCLUDES: Makefile
     steps:
     # Update GitHub status for dispatch events
@@ -124,7 +128,6 @@ jobs:
     if: ${{ github.event.client_payload.slash_command.args.unnamed.arg1 == 'bats' || github.event.client_payload.slash_command.arg1 == 'bats' || github.event.client_payload.slash_command.args.unnamed.arg1 == 'all' || github.event.client_payload.slash_command.arg1 == 'all' }}
     container: cloudposse/testing.cloudposse.co:latest
     env: 
-      PATH: "/usr/local/terraform/0.12/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
       MAKE_INCLUDES: Makefile
     steps:
     # Update GitHub status for dispatch events
@@ -148,6 +151,35 @@ jobs:
         token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
         repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
         ref: ${{ github.event.client_payload.pull_request.head.ref }} 
+
+    # Determine requied version of terraform based on the target branch of the pull request. Then update the PATH to use it.
+    - name: "Determine required terraform version"
+      run: |
+        VERSION=$(cut -d/ -f1 <<<${BASE_REF})
+        if [[ ${VERSION} == 'master' ]]; then
+          VERSION=0.12
+        fi
+
+        # Match lables like `terraform/0.12` or nothing (to prevent non-zero exit code) 
+        OVERRIDE_VERSION=$(grep -Eo '(terraform/\d+\.\d+|)' <<<${LABELS} | cut -d/ -f2)
+
+        if [ -n "${OVERRIDE_VERSION}" ]; then
+          VERSION=${OVERRIDE_VERSION}
+          echo "Terraform ${VERSION} is required based on labels..."
+        else
+          echo "Terraform ${VERSION} is required for ${BASE_REF}..."
+        fi
+
+        if [ -x "/usr/local/terraform/${VERSION}/bin/terraform" ]; then
+          printf "::set-env name=PATH::/usr/local/terraform/%s/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n" ${VERSION}
+        else
+          echo "Unable to locate executable for terraform ${VERSION}"
+          exit 1
+        fi
+      env:
+        # Pull request target branch
+        BASE_REF: ${{ github.event.client_payload.pull_request.base.ref }}
+        LABELS: ${{ join(github.event.client_payload.pull_request.labels.*.name, '\n') }}
 
     # Initialize the test-harness which has a library of bats tests
     - name: "Initialize test-harness"
@@ -212,7 +244,6 @@ jobs:
     if: ${{ github.event.client_payload.slash_command.args.unnamed.arg1 == 'terratest' || github.event.client_payload.slash_command.arg1 == 'terratest' || github.event.client_payload.slash_command.args.unnamed.arg1 == 'all' || github.event.client_payload.slash_command.arg1 == 'all' }}
     container: cloudposse/testing.cloudposse.co:latest
     env: 
-      PATH: "/usr/local/terraform/0.12/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
       MAKE_INCLUDES: Makefile
     steps:
     # Update GitHub status for dispatch events
@@ -236,6 +267,35 @@ jobs:
         token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
         repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
         ref: ${{ github.event.client_payload.pull_request.head.ref }} 
+
+    # Determine requied version of terraform based on the target branch of the pull request. Then update the PATH to use it.
+    - name: "Determine required terraform version"
+      run: |
+        VERSION=$(cut -d/ -f1 <<<${BASE_REF})
+        if [[ ${VERSION} == 'master' ]]; then
+          VERSION=0.12
+        fi
+
+        # Match lables like `terraform/0.12` or nothing (to prevent non-zero exit code) 
+        OVERRIDE_VERSION=$(grep -Eo '(terraform/\d+\.\d+|)' <<<${LABELS} | cut -d/ -f2)
+
+        if [ -n "${OVERRIDE_VERSION}" ]; then
+          VERSION=${OVERRIDE_VERSION}
+          echo "Terraform ${VERSION} is required based on labels..."
+        else
+          echo "Terraform ${VERSION} is required for ${BASE_REF}..."
+        fi
+
+        if [ -x "/usr/local/terraform/${VERSION}/bin/terraform" ]; then
+          printf "::set-env name=PATH::/usr/local/terraform/%s/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n" ${VERSION}
+        else
+          echo "Unable to locate executable for terraform ${VERSION}"
+          exit 1
+        fi
+      env:
+        # Pull request target branch
+        BASE_REF: ${{ github.event.client_payload.pull_request.base.ref }}
+        LABELS: ${{ join(github.event.client_payload.pull_request.labels.*.name, '\n') }}
 
     # Initialize the terratest go project
     - name: "Initialize terratest go project"
